export const BEGGIN_API_CALL = 'BEGGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const TOGGLE_MENU_VISIBLE = 'TOGGLE_MENU_VISIBLE';

export const AAD_INITIALIZING = 'AAD_INITIALIZING';
export const AAD_LOGIN_SUCCESS = 'AAD_LOGIN_SUCCESS';
export const AAD_LOGOUT_SUCCESS = 'AAD_LOGOUT_SUCCESS';
