export const BEGGIN_API_CALL = 'BEGGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const TOGGLE_MENU_VISIBLE = 'TOGGLE_MENU_VISIBLE';

export const AAD_INITIALIZING = 'AAD_INITIALIZING';
export const AAD_LOGIN_SUCCESS = 'AAD_LOGIN_SUCCESS';
export const AAD_LOGOUT_SUCCESS = 'AAD_LOGOUT_SUCCESS';

export const CREATE_WATER_SUCCESS = 'CREATE_WATER_SUCCESS';
export const GET_WATER_BY_ID_SUCCESS = 'GET_WATER_BY_ID_SUCCESS';
export const UPDATE_WATER_SUCCESS = 'UPDATE_WATER_SUCCESS';
export const DELETE_WATER_SUCCESS = 'DELETE_WATER_SUCCESS';
export const LOAD_WATER_SUCCESS = 'LOAD_WATER_SUCCESS';

export const SW_INIT = 'SW_INIT';
export const SW_UPDATE = 'SW_UPDATE';
